---
version: "2.1"
services:
  minetest_zfn_00:
    image: ghcr.io/linuxserver/luanti:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_00
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname 00 --world worlds --port 30140 --logfile /config/.minetest/logs/00.log
    volumes:
      - ./:/config/.minetest
    ports:
      - 30140:30140/udp
    restart: unless-stopped

