---
version: "2.1"
services:
  minetest_zfn_08:
    image: ghcr.io/linuxserver/luanti:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_08
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname 08 --world worlds --port 30108 --logfile /config/.minetest/logs/08.log
    volumes:
      - .:/config/.minetest
      - ./config-08/minetest.conf:/config/.minetest/main-config/minetest.conf
    ports:
      - 30108:30108/udp
    restart: unless-stopped

