---
version: "2.1"
services:
  minetest_zfn_12:
    image: ghcr.io/linuxserver/minetest:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_12
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname 12 --world worlds --port 30112 --logfile /config/.minetest/logs/12.log
    volumes:
      - ./:/config/.minetest
    ports:
      - 30112:30112/udp
    restart: unless-stopped

