---
version: "2.1"
services:
  minetest_zfn_16:
    image: ghcr.io/linuxserver/luanti:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_16
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname 16 --world worlds --port 30116 --logfile /config/.minetest/logs/16.log
    volumes:
      - ./:/config/.minetest
    ports:
      - 30116:30116/udp
    restart: unless-stopped

