---
version: "2.1"
services:
  minetest_zfn_19:
    image: ghcr.io/linuxserver/luanti:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_19
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname 19 --world worlds --port 30119 --logfile /config/.minetest/logs/19.log
    volumes:
      - ./:/config/.minetest
    ports:
      - 30119:30119/udp
    restart: unless-stopped

