---
services:
  minetest:
    image: ghcr.io/linuxserver/luanti:latest
    container_name: minetest_zfn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname $WORLDNAME --world worlds --logfile /config/.minetest/logs/$WORLDNAME.log --port 30000"
    volumes:
      - ./:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped

